apiVersion: apps/v1
kind: Deployment
metadata:
  name: footballclubsmanager
  labels:
    app: footballclubsmanager
spec:
  replicas: 4
  selector:
    matchLabels:
      app: footballclubsmanager
  template:
    metadata:
      labels:
        app: footballclubsmanager
    spec:
      containers:
        - name: footballclubsmanager
          imagePullPolicy: Always
          image: ghcr.io/viertor/asp.net_mvc-footballclubsmanager:k8s_training_kasia
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
             memory: "128Mi"
             cpu: "500m"
          readinessProbe:
            exec: 
              command:
              - sh
              - -cc
              - curl http://localhost:5005/FootballClubs/Details | grep "name\":\"RKS Radomsko"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second
  labels:
    app: second
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second
  template:
    metadata:
      labels:
        app: second
    spec:
      containers:
        - name: second
          image: nginx
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
             memory: "128Mi"
             cpu: "500m"
