apiVersion: apps/v1
kind: Deployment
metadata:
  name: footballclubsmanager
  labels:
    app: footballclubsmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: footballclubsmanager
  template:
    metadata:
      labels:
        app: footballclubsmanager
    spec:
      containers:
        - name: footballclubsmanager
          image: ghcr.io/viertor/asp.net_mvc-footballclubsmanager:k8s_traning_lukasz
